CREATE DATABASE PROYECTODB;
GO

USE PROYECTODB;
GO

CREATE TABLE ACTIVIDADES_FINANCIERAS (
    IDACTIVIDADFINANCIERA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBREACTIVIDADFINANCIERA VARCHAR(30) NOT NULL,
    DESCRIPCIONACTIVIDADFINANCIERA VARCHAR(150) NOT NULL,
    NIVELDERIESGO INT NOT NULL CHECK (NIVELDERIESGO IN (1, 2, 3)),
    FECHADEREGISTRO DATETIME NOT NULL,
    FECHADEMODIFICACION DATETIME NULL,
    ESTADO BIT NOT NULL
);
GO
CREATE TABLE PERSONAS (
    IDPERSONA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDENTIFICACIONPERSONA VARCHAR(30) NOT NULL UNIQUE,
    TIPOIDENTIFICACION INT NOT NULL CHECK (TIPOIDENTIFICACION IN (1, 2)), -- 1 Fisica, 2 Juridica
    NOMBREPERSONA VARCHAR(100) NOT NULL,
    PRIMERAPELLIDOPERSONA VARCHAR(100) NULL,
    SEGUNDOAPELLIDOPERSONA VARCHAR(100) NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    CORREOELECTRONICO VARCHAR(200) NOT NULL,
    DIRECCION VARCHAR(500) NOT NULL,
    ESTADODERIESGO INT NOT NULL CHECK (ESTADODERIESGO IN (0, 1, 2, 3, 4)), -- 0 Sin analisis ... 4 Critico
    FECHADEREGISTRO DATETIME NOT NULL,
    FECHADEMODIFICACION DATETIME NOT NULL,
    ESTADO BIT NOT NULL  -- 1 Activo, 0 Inactivo
);
GO


-- TABLA: ACTIVIDADES_PERSONA

CREATE TABLE ACTIVIDADES_PERSONA (
    IDACTIVIDADPERSONA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDACTIVIDADFINANCIERA INT NOT NULL FOREIGN KEY REFERENCES ACTIVIDADES_FINANCIERAS(IDACTIVIDADFINANCIERA),
    IDPERSONA INT NOT NULL FOREIGN KEY REFERENCES PERSONAS(IDPERSONA),
    FECHADEREGISTRO DATETIME NOT NULL,
    FECHADEMODIFICACION DATETIME NULL,
    ESTADO BIT NOT NULL  
);
GO


-- TABLA: BITACORA_EVENTOS

CREATE TABLE BITACORA_EVENTOS (
    IDEVENTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TABLADEEVENTO VARCHAR(20) NOT NULL,
    TIPODEEVENTO VARCHAR(20) NOT NULL,
    FECHADEEVENTO DATETIME NOT NULL,
    DESCRIPCIONDEEVENTO VARCHAR(MAX) NOT NULL,
    STACKTRACE VARCHAR(MAX) NULL,
    DATOSANTERIORES VARCHAR(MAX) NULL,
    DATOSPOSTERIORES VARCHAR(MAX) NULL
);
GO

INSERT INTO ACTIVIDADES_FINANCIERAS 
(NOMBREACTIVIDADFINANCIERA, DESCRIPCIONACTIVIDADFINANCIERA, NIVELDERIESGO, FECHADEREGISTRO, FECHADEMODIFICACION, ESTADO)
VALUES 
('INVERSION EN BONOS', 'COMPRA DE BONOS DEL ESTADO CON RIESGO MINIMO', 1, GETDATE(), NULL, 1);
GO

INSERT INTO ACTIVIDADES_FINANCIERAS 
(NOMBREACTIVIDADFINANCIERA, DESCRIPCIONACTIVIDADFINANCIERA, NIVELDERIESGO, FECHADEREGISTRO, FECHADEMODIFICACION, ESTADO)
VALUES 
('COMPRA DE ACCIONES', 'INVERSION EN ACCIONES DE EMPRESAS NACIONALES', 2, GETDATE(), NULL, 1);
GO

INSERT INTO ACTIVIDADES_FINANCIERAS 
(NOMBREACTIVIDADFINANCIERA, DESCRIPCIONACTIVIDADFINANCIERA, NIVELDERIESGO, FECHADEREGISTRO, FECHADEMODIFICACION, ESTADO)
VALUES 
('CRIPTOMONEDAS', 'INVERSION EN ACTIVOS DIGITALES DE ALTA VOLATILIDAD', 3, GETDATE(), NULL, 1);
GO

CREATE TABLE ArchivosAnalisis (
    IdArchivo INT IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(10) NOT NULL,
    TextoDelArchivo VARCHAR(MAX) NOT NULL,
    Fuente VARCHAR(2000) NOT NULL,
    FechaDeRegistro DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE BITACORA_EVENTOS (
    IdEvento INT PRIMARY KEY IDENTITY(1,1),
    TablaDeEvento VARCHAR(20) NOT NULL,
    TipoDeEvento VARCHAR(20) NOT NULL,
    FechaDeEvento DATETIME NOT NULL,
    DescripcionDeEvento VARCHAR(MAX) NOT NULL,
    StackTrace VARCHAR(MAX) NULL,
    DatosAnteriores VARCHAR(MAX) NULL,
    DatosPosteriores VARCHAR(MAX) NULL
);

